### PR TITLE
issue 23/ adding fetch prefect details in coordinator type

### PR DESCRIPTION
**Pull request by JWhacheng**
Coordinator model, mutation, and types update.

### CODE REVIEW

**Comment by JWhacheng** [comment]
@DesignrKnight , @riteshsp2000  I cannot set a reviewer neither set the issue. This PR Resolves #23

**Comment by DesignrKnight** [comment]
Thank you so much @JWhacheng for your PR. Will review

**Review by DesignrKnight — APPROVED** [review]

**Comment by DesignrKnight** [comment]
@all-contributors add @JWhacheng for code

**Comment by DesignrKnight** [comment]
### Hacktoberfest Thank You from NIT Rourkela community
It was a super fun experience in Hacktoberfest with you. We hope you also had fun and amazing learning. We look forward to you in our upcoming sessions and events as part of the community. 
You can join our Slack community at http://bit.ly/NITRDevs

**As a token of our gratitude, we have set up digital badges of recognition for our contributors from Hacktoberfest. 
Do claim yours at https://live.dscnitrourkela.org/**

Thanks and Cheers!
Stay Safe

**Pull request merged**
