### PR TITLE
fix: prevent duplicate creation for mentee and mentor

### LINKED ISSUE #25: Prevent Duplicate creation
**Describe the bug**
- While creating a new user (be that any of the 4 types), the user is directly saved to the database without checking if there exists a previous user with same details.

**Expected behavior**
- Before saving to the database, checks should be made to see if an existing user with the same **Roll Number** exists or not. If not, proceed with saving. If yes throw an error.

### PR DESCRIPTION
**Pull request by yigitcukuren**
Fixes #25

### CODE REVIEW

**Comment by DesignrKnight** [comment]
@riteshsp2000 , do review and also from my first glance, it looks good. It adds check for mentor and mentee.
Will be good if we also have for coordinator and prefect also

**Comment by DesignrKnight** [comment]
This is good @yigitcukuren . We request you to wait for one of the maintainers to assign/confirm before you start working as we want to make sure your contributions can be merged easily. 

Thanks again for your contribution

**Review by riteshsp2000 — CHANGES_REQUESTED** [review]
This looks could. Could you do the same for Prefect and Coordinators as well? 

Currently there aren't rollnumbers in their definitions. A PR has been made for the same.
I'll merge the PR, you can probably fetch and do the necessary changes. 

Also it would be great if you could work on a separate branch named the feature/work in short instead of working on your master. Just as a part of the convention.

**Comment by riteshsp2000** [comment]
@yigitcukuren The master branch has been updated, you can pull from it and work on the prefect and coordinator mutations

**Comment by yigitcukuren** [comment]
Hey @riteshsp2000 

I have just created another PR using a feature branch. Please see #28.

**Pull request closed without merging**
