### PR TITLE
fix(schema): prevent duplication user creation

### LINKED ISSUE #25: Prevent Duplicate creation
**Describe the bug**
- While creating a new user (be that any of the 4 types), the user is directly saved to the database without checking if there exists a previous user with same details.

**Expected behavior**
- Before saving to the database, checks should be made to see if an existing user with the same **Roll Number** exists or not. If not, proceed with saving. If yes throw an error.

### PR DESCRIPTION
**Pull request by yigitcukuren**
Fixes #25

I have just added check for all user types.

### CODE REVIEW

**Review by riteshsp2000 — APPROVED** [review]
Okay, everything looks great!

**Comment by DesignrKnight** [comment]
@riteshsp2000 
Go ahead and merge

**Review by DesignrKnight — APPROVED** [review]

**Comment by riteshsp2000** [comment]
@all-contributors please add @yigitcukuren for tests

**Comment by DesignrKnight** [comment]
### Hacktoberfest Thank You from NIT Rourkela community
It was a super fun experience in Hacktoberfest with you. We hope you also had fun and amazing learning. We look forward to you in our upcoming sessions and events as part of the community. 
You can join our Slack community at http://bit.ly/NITRDevs

**As a token of our gratitude, we have set up digital badges of recognition for our contributors from Hacktoberfest. 
Do claim yours at https://live.dscnitrourkela.org/**

Thanks and Cheers!
Stay Safe

**Pull request merged**
