### PR TITLE
Update for ICS Database 2020

### LINKED ISSUE #39: Flatten the Coordinator model to have prefect is at same level as _id

### PR DESCRIPTION
**Pull request by DesignrKnight**
Link Types by Roll Number instead of Roll Number

### CODE REVIEW

**Comment by DesignrKnight** [comment]
https://project-avocado-8b3e1.uc.r.appspot.com/graphql
Yo

**Comment by DesignrKnight** [comment]
image
image
image

**Comment by DesignrKnight** [comment]
Approve when free @riteshsp2000 
Do not merge yet. Will do once we are double sure after Astha finishes app part
This is already deployed to App Engine from localhost

**Comment by riteshsp2000** [comment]
Hey @DesignrKnight, I checked all the queries... they are working great. But there are errors with coordinator mutations. The changes that you did for types, models ... those changes need to be done for mutations as well.

**Comment by DesignrKnight** [comment]
Will do before merge

**Comment by abhibhaw** [comment]
Wow PR opened since 2020 🎉 🎉

**Comment by abhibhaw** [comment]
These changes have already been handled in the recent refactoring #60

**Pull request closed without merging**
